nelmio_api_doc:
    documentation:
        info:
            title: Planers
            description: API for Planers
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1
