version: '3'

services:
  mysql:
      image: mysql:5.7
      command: mysqld --sql-mode="NO_ENGINE_SUBSTITUTION"
      ports:
        - "3307:3306"
      volumes:
        - ./backups/:/backups/
        - ./docker/mysql/:/docker-entrypoint-initdb.d/
      environment:
        - MYSQL_DATABASE=project
        - MYSQL_USER=developer
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_PASSWORD=password

  php-fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
      args:
        environment: dev
    volumes:
      - ./:/usr/src/app
      - "~/.composer.sh:/root/.composer.sh"
      - "~/.ssh:/root/.ssh-local:ro"
    depends_on:
      - mysql
    environment:
      - LOCAL_ENV=1
      - COMPOSER_ALLOW_SUPERUSER=1
      - PHP_IDE_CONFIG=serverName=Planers
      - LOG_PATH=%kernel.logs_dir%/%kernel.environment%.log

  nginx:
    image: nginx:latest
    ports:
      - "11170:80"
    volumes:
      - ./:/usr/src/app
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php-fpm
